language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sarithf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarithf/docker-react npm run test -- --coverage