language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sarithf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarithf/docker-react npm run test -- --coverage

deploy:
  - provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-2-497326278112"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY"
#changed key



